version: '3'

services:
  mysql-db:
    image: test-mysql-db:0.1
    build: ./docker/mysql/.
    environment:
      - MYSQL_USER=$DB_USER
      - MYSQL_HOST=$DB_HOST
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_SCHEMA
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PWD
    ports:
      - 3306:3306